package exceptionTest;

public class ExceptionTest {
	public static void main(String[] args) {
//		int [] arData=new int[5];
//		
//		try {
//		arData[5]=100;
//		}
//		catch(ArrayIndexOutOfBoundsException e){
//				System.out.println("실행할 수 없는 코드입니다");
//			}
//			System.out.println("무조건 실행해야 하는 문장");	
		
		
//		try {
//			System.out.println(10/0);
//			System.out.println("실행할 수 없는 코드입니다");
//		}
//		catch(ArithmeticException e) {
//			System.out.println("무조건 실행해야 하는 문장");
//		}
		
//		try {
//	         System.out.println(10 / 0);
//	      } catch (NumberFormatException e) {
//	         System.out.println("0으로 나눌 수 없어요!");
//	      } finally {
//	         System.out.println("무조건 실행해야 하는 문장");
//	      }
		
		
		
		
	}
}
